version: '3.9'

services:
   postgres:
      image: postgres:16-alpine
      container_name: ecolna_postgres
      environment:
         POSTGRES_USER: ${POSTGRES_USER:-postgres}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
         POSTGRES_DB: ${POSTGRES_DB:-ecolna}
      ports:
         - '${HOST_PG_PORT:-5433}:5432'
      volumes:
         - pgdata:/var/lib/postgresql/data
      healthcheck:
         test:
            [
               'CMD-SHELL',
               'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-ecolna}',
            ]
         interval: 5s
         timeout: 5s
         retries: 5
      restart: unless-stopped

volumes:
   pgdata:
